In [1]:
import pandas as pd
import numpy as np
import os

In [ ]:
# define path
VISITS_INPUT = r"C:\Users\Dell\Desktop\Geopulse\store_visits.csv"

SUMMARY_INPUT = r"C:\Users\Dell\Desktop\Geopulse\footfall_summary.csv"

print("Store visits input:", VISITS_INPUT)
print("Footfall summary input:", SUMMARY_INPUT)

Store visits input: C:\Users\Dell\Desktop\Geopulse\store_visits.csv
Footfall summary input: C:\Users\Dell\Desktop\Geopulse\footfall_summary.csv

In [ ]:
# Check files

print(
    "store_visits.csv exists:",
    os.path.exists(VISITS_INPUT)
)

print(
    "footfall_summary.csv exists:",
    os.path.exists(SUMMARY_INPUT)
)

store_visits.csv exists: True
footfall_summary.csv exists: True

In [11]:
# Load store_visits.csv

visits = pd.read_csv(VISITS_INPUT)

print("Store visits loaded successfully!")

print("Rows:", visits.shape[0])
print("Columns:", visits.shape[1])

Store visits loaded successfully!
Rows: 85
Columns: 12

In [12]:
# Understand the store-visits structure

visits.head(10)

,visit_id,device_id,persona,store_id,store_name,category,entry_time,exit_time,dwell_minutes,ping_count,date,day_of_week
0,1642c621-fd40-4079-a7dd-cfa3df7fff25,6a0a265a-94fb-4de8-afdf-82167d59aee1,Shopper,STR003,Store C - Wardha Road,Hypermarket,2026-08-10 12:08:00,2026-08-10 13:35:00,87.0,30,2026-08-10,Monday
1,de46c3f2-e240-4e75-8d19-4f61d9564e5f,dc022692-fed8-434c-a753-6e27982acfec,Shopper,STR001,Store A - Sitabuldi,Supermarket,2026-08-10 10:48:00,2026-08-10 12:03:00,75.0,26,2026-08-10,Monday
2,13e8bfb1-5c63-4ce8-99ee-3a669778859d,7049c16f-850d-4d82-83ba-86d394baad62,Shopper,STR002,Store B - Civil Lines,Mall,2026-08-10 12:12:00,2026-08-10 13:12:00,60.0,21,2026-08-10,Monday
3,e65d189f-a145-4b92-9a29-482ada32128b,2c42d42d-8bd2-4f7a-8625-ca4abbd3ae36,Shopper,STR002,Store B - Civil Lines,Mall,2026-08-10 11:33:00,2026-08-10 12:09:00,36.0,13,2026-08-10,Monday
4,e0b8205a-9837-47c3-a8b2-4ec69920f874,bc10021b-2dce-4208-a095-9ff7dde49a09,Shopper,STR001,Store A - Sitabuldi,Supermarket,2026-08-10 12:24:00,2026-08-10 13:18:00,54.0,19,2026-08-10,Monday
5,52d27105-00f6-4dcd-b998-af1f3f520318,313b23f5-b761-4fb5-b6c2-eb69d3b4120a,Shopper,STR001,Store A - Sitabuldi,Supermarket,2026-08-10 11:06:00,2026-08-10 11:15:00,9.0,4,2026-08-10,Monday
6,1e1a5237-6b14-46f1-9309-dd7209a841e1,313b23f5-b761-4fb5-b6c2-eb69d3b4120a,Shopper,STR001,Store A - Sitabuldi,Supermarket,2026-08-10 11:21:00,2026-08-10 12:09:00,48.0,17,2026-08-10,Monday
7,82352725-abdb-4b87-886e-cfcf2b944490,2dba3554-dfcf-4822-8b0d-1994366dfb0d,Shopper,STR001,Store A - Sitabuldi,Supermarket,2026-08-10 10:28:00,2026-08-10 11:31:00,63.0,22,2026-08-10,Monday
8,46cf57f0-192f-4d8a-8ef7-b7c9a374bfea,2075b779-eb75-4544-b241-6fa029db2db3,Shopper,STR003,Store C - Wardha Road,Hypermarket,2026-08-10 11:51:00,2026-08-10 12:00:00,9.0,4,2026-08-10,Monday
9,2fb9ea67-9c36-4584-931d-fa63811b0e1e,2075b779-eb75-4544-b241-6fa029db2db3,Shopper,STR003,Store C - Wardha Road,Hypermarket,2026-08-10 12:06:00,2026-08-10 13:21:00,75.0,26,2026-08-10,Monday

In [13]:
# Column names

for i, column in enumerate(
    visits.columns,
    start=1
):
    print(i, "→", column)

1 → visit_id
2 → device_id
3 → persona
4 → store_id
5 → store_name
6 → category
7 → entry_time
8 → exit_time
9 → dwell_minutes
10 → ping_count
11 → date
12 → day_of_week

In [14]:
# data types

visits.dtypes

visit_id          object
device_id         object
persona           object
store_id          object
store_name        object
category          object
entry_time        object
exit_time         object
dwell_minutes    float64
ping_count         int64
date              object
day_of_week       object
dtype: object

In [15]:
# dataset information

visits.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85 entries, 0 to 84
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   visit_id       85 non-null     object
 1   device_id      85 non-null     object
 2   persona        85 non-null     object
 3   store_id       85 non-null     object
 4   store_name     85 non-null     object
 5   category       85 non-null     object
 6   entry_time     85 non-null     object
 7   exit_time      85 non-null     object
 8   dwell_minutes  85 non-null     float64
 9   ping_count     85 non-null     int64
 10  date           85 non-null     object
 11  day_of_week    85 non-null     object
dtypes: float64(1), int64(1), object(10)
memory usage: 8.1+ KB

In [16]:
# statistical summary

visits.describe()

       dwell_minutes  ping_count
count      85.000000   85.000000
mean       58.411765   20.470588
std        23.143596    7.714532
min         9.000000    4.000000
25%        42.000000   15.000000
50%        57.000000   20.000000
75%        78.000000   27.000000
max        99.000000   34.000000

In [17]:
# Check missing values

missing = pd.DataFrame({
    "Missing_Count": visits.isnull().sum(),
    "Missing_Percentage": (
        visits.isnull().sum()
        / len(visits)
        * 100
    ).round(2)
})

missing

               Missing_Count  Missing_Percentage
visit_id                   0                 0.0
device_id                  0                 0.0
persona                    0                 0.0
store_id                   0                 0.0
store_name                 0                 0.0
category                   0                 0.0
entry_time                 0                 0.0
exit_time                  0                 0.0
dwell_minutes              0                 0.0
ping_count                 0                 0.0
date                       0                 0.0
day_of_week                0                 0.0

In [18]:
# Check duplicate records

print(
    "Duplicate complete rows:",
    visits.duplicated().sum()
)

Duplicate complete rows: 0

In [19]:
# check duplicate visit IDs
print(
    "Total visits:",
    len(visits)
)

print(
    "Unique visit IDs:",
    visits["visit_id"].nunique()
)

print(
    "Duplicate visit IDs:",
    visits["visit_id"].duplicated().sum()
)

Total visits: 85
Unique visit IDs: 85
Duplicate visit IDs: 0

In [20]:
# Clean text columns

text_columns = [
    "visit_id",
    "device_id",
    "persona",
    "store_id",
    "store_name",
    "category",
    "day_of_week"
]

for column in text_columns:

    visits[column] = (
        visits[column]
        .astype("string")
        .str.strip()
    )

In [21]:
# Convert timestamps

visits["entry_time"] = pd.to_datetime(
    visits["entry_time"],
    errors="coerce"
)

visits["exit_time"] = pd.to_datetime(
    visits["exit_time"],
    errors="coerce"
)

In [22]:
# Check timestamp problems

print(
    "Invalid entry times:",
    visits["entry_time"].isna().sum()
)

print(
    "Invalid exit times:",
    visits["exit_time"].isna().sum()
)

Invalid entry times: 0
Invalid exit times: 0

In [23]:
# Validate entry and exit time

invalid_times = (
    visits["exit_time"]
    < visits["entry_time"]
)

print(
    "Invalid visit time records:",
    invalid_times.sum()
)

Invalid visit time records: 0

In [24]:
# Validate dwell time

print(
    visits["dwell_minutes"].describe()
)

count    85.000000
mean     58.411765
std      23.143596
min       9.000000
25%      42.000000
50%      57.000000
75%      78.000000
max      99.000000
Name: dwell_minutes, dtype: float64

In [25]:
# check negative values

invalid_dwell = (
    visits["dwell_minutes"] < 0
)

print(
    "Negative dwell times:",
    invalid_dwell.sum()
)

Negative dwell times: 0

In [26]:
# checking minimum

print(
    "Minimum dwell:",
    visits["dwell_minutes"].min()
)

print(
    "Minimum required dwell:",
    5
)

Minimum dwell: 9.0
Minimum required dwell: 5

In [27]:
# Recalculate dwell time

calculated_dwell = (
    visits["exit_time"]
    - visits["entry_time"]
).dt.total_seconds() / 60

visits["calculated_dwell_minutes"] = (
    calculated_dwell.round(1)
)

In [28]:
visits[
    [
        "dwell_minutes",
        "calculated_dwell_minutes"
    ]
].head(10)

   dwell_minutes  calculated_dwell_minutes
0           87.0                      87.0
1           75.0                      75.0
2           60.0                      60.0
3           36.0                      36.0
4           54.0                      54.0
5            9.0                       9.0
6           48.0                      48.0
7           63.0                      63.0
8            9.0                       9.0
9           75.0                      75.0

In [29]:
# Find dwell-time inconsistencies

dwell_difference = (
    visits["dwell_minutes"]
    - visits["calculated_dwell_minutes"]
).abs()

print(
    "Maximum dwell difference:",
    dwell_difference.max()
)

Maximum dwell difference: 0.0

In [30]:
# Remove temporary column

visits.drop(
    columns=["calculated_dwell_minutes"],
    inplace=True
)

In [31]:
# Validate ping count

print(
    visits["ping_count"].describe()
)

count    85.000000
mean     20.470588
std       7.714532
min       4.000000
25%      15.000000
50%      20.000000
75%      27.000000
max      34.000000
Name: ping_count, dtype: float64

In [32]:
invalid_ping_count = (
    visits["ping_count"] <= 0
)

print(
    "Invalid ping counts:",
    invalid_ping_count.sum()
)

Invalid ping counts: 0

In [33]:
# Validate store IDs

print(
    visits["store_id"].value_counts()
)

store_id
STR002    33
STR001    30
STR003    22
Name: count, dtype: Int64

In [34]:
valid_store_ids = {
    "STR001",
    "STR002",
    "STR003"
}

invalid_stores = ~visits["store_id"].isin(
    valid_store_ids
)

print(
    "Invalid store IDs:",
    invalid_stores.sum()
)

Invalid store IDs: 0

In [35]:
# Validate personas

print(
    visits["persona"].value_counts()
)

persona
Shopper    85
Name: count, dtype: Int64

In [36]:
# Recreate date from entry time

visits["date"] = (
    visits["entry_time"]
    .dt.date
)

In [37]:
# Recreate day of week

visits["day_of_week"] = (
    visits["entry_time"]
    .dt.day_name()
)

In [38]:
# Final store-visits quality check

print("Rows:", len(visits))
print("Columns:", len(visits.columns))

print(
    "\nMissing values:"
)

print(
    visits.isnull().sum()
)

print(
    "\nDuplicate rows:",
    visits.duplicated().sum()
)

print(
    "\nDuplicate visit IDs:",
    visits["visit_id"].duplicated().sum()
)

Rows: 85
Columns: 12

Missing values:
visit_id         0
device_id        0
persona          0
store_id         0
store_name       0
category         0
entry_time       0
exit_time        0
dwell_minutes    0
ping_count       0
date             0
day_of_week      0
dtype: int64

Duplicate rows: 0

Duplicate visit IDs: 0

In [39]:
# Sort store visits

visits = visits.sort_values(
    by=[
        "store_id",
        "entry_time",
        "device_id"
    ]
).reset_index(drop=True)

In [40]:
# Save cleaned store visits

os.makedirs(
    "data/processed",
    exist_ok=True
)

visits.to_csv(
    VISITS_OUTPUT,
    index=False
)

print(
    "Clean store visit dataset saved!"
)

print(
    VISITS_OUTPUT
)

Clean store visit dataset saved!
data/processed/store_visits_clean.csv

In [41]:
# footfall_summary.csv
# Load summary

summary = pd.read_csv(
    SUMMARY_INPUT
)

print(
    "Footfall summary loaded!"
)

print(
    "Rows:",
    summary.shape[0]
)

print(
    "Columns:",
    summary.shape[1]
)

Footfall summary loaded!
Rows: 3
Columns: 8

In [43]:
# Inspect structure

summary.head()

,store_id,store_name,category,date,total_visits,total_dwell_minutes,unique_visitors,avg_dwell_minutes
0,STR003,Store C - Wardha Road,Hypermarket,2026-08-10,22,1446.0,20,65.7
1,STR001,Store A - Sitabuldi,Supermarket,2026-08-10,30,1689.0,27,56.3
2,STR002,Store B - Civil Lines,Mall,2026-08-10,33,1830.0,30,55.5

In [44]:
summary.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   store_id             3 non-null      object
 1   store_name           3 non-null      object
 2   category             3 non-null      object
 3   date                 3 non-null      object
 4   total_visits         3 non-null      int64
 5   total_dwell_minutes  3 non-null      float64
 6   unique_visitors      3 non-null      int64
 7   avg_dwell_minutes    3 non-null      float64
dtypes: float64(2), int64(2), object(4)
memory usage: 324.0+ bytes

In [45]:
summary.dtypes

store_id                object
store_name              object
category                object
date                    object
total_visits             int64
total_dwell_minutes    float64
unique_visitors          int64
avg_dwell_minutes      float64
dtype: object

In [46]:
# Check missing values

summary_missing = pd.DataFrame({
    "Missing_Count": summary.isnull().sum(),

    "Missing_Percentage": (
        summary.isnull().sum()
        / len(summary)
        * 100
    ).round(2)
})

summary_missing

                     Missing_Count  Missing_Percentage
store_id                         0                 0.0
store_name                       0                 0.0
category                         0                 0.0
date                             0                 0.0
total_visits                     0                 0.0
total_dwell_minutes              0                 0.0
unique_visitors                  0                 0.0
avg_dwell_minutes                0                 0.0

In [47]:
# Check duplicates

print(
    "Duplicate rows:",
    summary.duplicated().sum()
)

Duplicate rows: 0

In [48]:
duplicate_store_date = summary.duplicated(
    subset=[
        "store_id",
        "date"
    ]
).sum()

print(
    "Duplicate store-date combinations:",
    duplicate_store_date
)

Duplicate store-date combinations: 0

In [49]:
# Clean summary text fields

summary_text_columns = [
    "store_id",
    "store_name",
    "category"
]

for column in summary_text_columns:

    summary[column] = (
        summary[column]
        .astype("string")
        .str.strip()
    )

In [50]:
# Convert summary date

summary["date"] = pd.to_datetime(
    summary["date"],
    errors="coerce"
)

In [51]:
print(
    "Invalid dates:",
    summary["date"].isna().sum()
)

Invalid dates: 0

In [52]:
# Convert numerical columns

numeric_columns = [
    "total_visits",
    "unique_visitors",
    "total_dwell_minutes",
    "avg_dwell_minutes"
]

for column in numeric_columns:

    summary[column] = pd.to_numeric(
        summary[column],
        errors="coerce"
    )

In [53]:
# Check summary statistics

summary[
    numeric_columns
].describe()

       total_visits  unique_visitors  total_dwell_minutes  avg_dwell_minutes
count      3.000000         3.000000             3.000000           3.000000
mean      28.333333        25.666667          1655.000000          59.166667
std        5.686241         5.131601           194.244691           5.672154
min       22.000000        20.000000          1446.000000          55.500000
25%       26.000000        23.500000          1567.500000          55.900000
50%       30.000000        27.000000          1689.000000          56.300000
75%       31.500000        28.500000          1759.500000          61.000000
max       33.000000        30.000000          1830.000000          65.700000

In [54]:
# Validate total visits

invalid_visits = (
    summary["total_visits"] <= 0
)

print(
    "Invalid total visits:",
    invalid_visits.sum()
)

Invalid total visits: 0

In [55]:
# Validate unique visitors

invalid_unique_visitors = (
    (summary["unique_visitors"] <= 0)
    |
    (
        summary["unique_visitors"]
        > summary["total_visits"]
    )
)

print(
    "Invalid unique visitor records:",
    invalid_unique_visitors.sum()
)

Invalid unique visitor records: 0

In [56]:
# Validate dwell time

invalid_total_dwell = (
    summary["total_dwell_minutes"] < 0
)

invalid_avg_dwell = (
    summary["avg_dwell_minutes"] < 0
)

print(
    "Invalid total dwell:",
    invalid_total_dwell.sum()
)

print(
    "Invalid average dwell:",
    invalid_avg_dwell.sum()
)

Invalid total dwell: 0
Invalid average dwell: 0

In [57]:
# Cross-check average dwell

calculated_avg = (
    summary["total_dwell_minutes"]
    / summary["total_visits"]
).round(1)

summary["calculated_avg_dwell"] = calculated_avg

In [58]:
summary[
    [
        "avg_dwell_minutes",
        "calculated_avg_dwell"
    ]
]

   avg_dwell_minutes  calculated_avg_dwell
0               65.7                  65.7
1               56.3                  56.3
2               55.5                  55.5

In [59]:
# Check differences

avg_difference = (
    summary["avg_dwell_minutes"]
    - summary["calculated_avg_dwell"]
).abs()

print(
    "Maximum average dwell difference:",
    avg_difference.max()
)

Maximum average dwell difference: 0.0

In [60]:
summary.drop(
    columns=["calculated_avg_dwell"],
    inplace=True
)

In [61]:
# Validate store IDs

invalid_summary_stores = (
    ~summary["store_id"].isin(
        [
            "STR001",
            "STR002",
            "STR003"
        ]
    )
)

print(
    "Invalid store IDs:",
    invalid_summary_stores.sum()
)

Invalid store IDs: 0

In [62]:
# Final summary quality check

print(
    "Rows:",
    len(summary)
)

print(
    "\nMissing values:"
)

print(
    summary.isnull().sum()
)

print(
    "\nDuplicate rows:",
    summary.duplicated().sum()
)

print(
    "\nDuplicate store-date combinations:",
    summary.duplicated(
        subset=[
            "store_id",
            "date"
        ]
    ).sum()
)

Rows: 3

Missing values:
store_id               0
store_name             0
category               0
date                   0
total_visits           0
total_dwell_minutes    0
unique_visitors        0
avg_dwell_minutes      0
dtype: int64

Duplicate rows: 0

Duplicate store-date combinations: 0

In [63]:
# Save cleaned summary

summary = summary.sort_values(
    by=[
        "date",
        "store_id"
    ]
).reset_index(drop=True)

summary.to_csv(
    SUMMARY_OUTPUT,
    index=False
)

print(
    "Clean footfall summary saved!"
)

print(
    SUMMARY_OUTPUT
)

Clean footfall summary saved!
data/processed/footfall_summary_clean.csv

In [64]:
# Final report

print("=" * 60)
print("GEOPULSE FOOTFALL DATA CLEANING COMPLETED")
print("=" * 60)

print("\nSTORE VISITS")
print(
    "Rows:",
    len(visits)
)
print(
    "Unique visits:",
    visits["visit_id"].nunique()
)
print(
    "Stores:",
    visits["store_id"].nunique()
)

print("\nFOOTFALL SUMMARY")
print(
    "Rows:",
    len(summary)
)
print(
    "Stores:",
    summary["store_id"].nunique()
)
print(
    "Dates:",
    summary["date"].nunique()
)

print("\nOUTPUT FILES")
print(VISITS_OUTPUT)
print(SUMMARY_OUTPUT)

print("=" * 60)

============================================================
GEOPULSE FOOTFALL DATA CLEANING COMPLETED
============================================================

STORE VISITS
Rows: 85
Unique visits: 85
Stores: 3

FOOTFALL SUMMARY
Rows: 3
Stores: 3
Dates: 1

OUTPUT FILES
data/processed/store_visits_clean.csv
data/processed/footfall_summary_clean.csv
============================================================