In [1]:
import pandas as pd
import numpy as np
import os

In [ ]:
# loading dataset file
df = pd.read_csv(r"C:\Users\Dell\Desktop\Geopulse\gps_data_final.csv")

In [ ]:
# basic dataset dimensions
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

Number of rows: 121931
Number of columns: 13

In [5]:
# displaying the first 10 rows
df.head(10)

,lat,lon,timestamp,activity,device_id,persona,device_os,gps_accuracy_m,ping_id,sequence_no,date,day_of_week,distance_from_home_m
0,21.139344,79.063887,2026-08-10 07:23:00,Home,6a0a265a-94fb-4de8-afdf-82167d59aee1,Shopper,ios,8.5,1dbbb33c-6cc3-4104-89ce-6d345d88d972,0,2026-08-10,Monday,2483.7
1,21.139221,79.063878,2026-08-10 07:26:00,Home,6a0a265a-94fb-4de8-afdf-82167d59aee1,Shopper,ios,8.5,e8a0c2ec-3072-4c53-b663-33336aabafd6,1,2026-08-10,Monday,2496.6
2,21.139220,79.064092,2026-08-10 07:29:00,Home,6a0a265a-94fb-4de8-afdf-82167d59aee1,Shopper,ios,8.5,9ac9651f-32a5-4ebc-ab37-268f4c6e49b3,2,2026-08-10,Monday,2488.5
3,21.139439,79.063887,2026-08-10 07:32:00,Home,6a0a265a-94fb-4de8-afdf-82167d59aee1,Shopper,ios,8.5,b7caaf07-e1c9-455d-b000-8ce260971592,3,2026-08-10,Monday,2473.9
4,21.139308,79.063826,2026-08-10 07:35:00,Home,6a0a265a-94fb-4de8-afdf-82167d59aee1,Shopper,ios,8.5,fecaa005-b644-439b-86d7-e920685cc893,4,2026-08-10,Monday,2489.8
5,21.139437,79.064023,2026-08-10 07:38:00,Home,6a0a265a-94fb-4de8-afdf-82167d59aee1,Shopper,ios,8.5,840a5b4a-7847-4a8f-9cb0-5cf88cd7f96c,5,2026-08-10,Monday,2468.8
6,21.139490,79.064097,2026-08-10 07:41:00,Home,6a0a265a-94fb-4de8-afdf-82167d59aee1,Shopper,ios,8.5,aa21ddb5-c843-4091-9f7e-ac32458c10de,6,2026-08-10,Monday,2460.4
7,21.139364,79.064129,2026-08-10 07:44:00,Home,6a0a265a-94fb-4de8-afdf-82167d59aee1,Shopper,ios,8.5,6805d372-6646-45c5-be00-673603ac72b4,7,2026-08-10,Monday,2472.2
8,21.139613,79.063937,2026-08-10 07:47:00,Home,6a0a265a-94fb-4de8-afdf-82167d59aee1,Shopper,ios,8.5,58a36fdd-60a1-41fb-9653-d1fa3e0e1688,8,2026-08-10,Monday,2454.0
9,21.139359,79.064097,2026-08-10 07:50:00,Home,6a0a265a-94fb-4de8-afdf-82167d59aee1,Shopper,ios,8.5,4b3aaf7a-3d36-440f-ad70-830d13138e3d,9,2026-08-10,Monday,2473.9

In [6]:
# displaying the last records
df.tail()

,lat,lon,timestamp,activity,device_id,persona,device_os,gps_accuracy_m,ping_id,sequence_no,date,day_of_week,distance_from_home_m
121926,21.139558,79.064247,2026-08-10 15:29:00,Home,75ee5fe3-477b-4925-bb27-c501fe0dfb19,Resident,Android,7.7,0ed808d3-42c1-4199-8016-deadcd6b5bae,152,2026-08-10,Monday,2447.6
121927,21.139343,79.063862,2026-08-10 15:32:00,Home,75ee5fe3-477b-4925-bb27-c501fe0dfb19,Resident,Android,7.7,11b0bcd2-d694-47df-ba72-52a9d7ab4423,153,2026-08-10,Monday,2484.7
121928,21.139466,79.063750,2026-08-10 15:35:00,Home,75ee5fe3-477b-4925-bb27-c501fe0dfb19,Resident,Android,7.7,87fb14d8-357a-45ca-87af-0326adbcb803,154,2026-08-10,Monday,2476.6
121929,21.139173,79.063842,2026-08-10 15:38:00,Home,75ee5fe3-477b-4925-bb27-c501fe0dfb19,Resident,Android,7.7,acb0f8d1-5e5b-4432-913b-b43710be83a0,155,2026-08-10,Monday,2503.0
121930,21.139459,79.064207,2026-08-10 15:41:00,Home,75ee5fe3-477b-4925-bb27-c501fe0dfb19,Resident,Android,7.7,cbe0472e-e8a5-4a6f-bd91-92bdc40d69cc,156,2026-08-10,Monday,2459.4

In [7]:
# column names
df.columns

Index(['lat', 'lon', 'timestamp', 'activity', 'device_id', 'persona',
       'device_os', 'gps_accuracy_m', 'ping_id', 'sequence_no', 'date',
       'day_of_week', 'distance_from_home_m'],
      dtype='object')

In [8]:
# data tpyes
df.dtypes

lat                     float64
lon                     float64
timestamp                object
activity                 object
device_id                object
persona                  object
device_os                object
gps_accuracy_m          float64
ping_id                  object
sequence_no               int64
date                     object
day_of_week              object
distance_from_home_m    float64
dtype: object

In [9]:
# complete dataframe informantion
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 121931 entries, 0 to 121930
Data columns (total 13 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   lat                   121931 non-null  float64
 1   lon                   121931 non-null  float64
 2   timestamp             121931 non-null  object
 3   activity              121931 non-null  object
 4   device_id             121931 non-null  object
 5   persona               121931 non-null  object
 6   device_os             121931 non-null  object
 7   gps_accuracy_m        121931 non-null  float64
 8   ping_id               121931 non-null  object
 9   sequence_no           121931 non-null  int64
 10  date                  121931 non-null  object
 11  day_of_week           121931 non-null  object
 12  distance_from_home_m  121931 non-null  float64
dtypes: float64(4), int64(1), object(8)
memory usage: 12.1+ MB

In [10]:
# statistical summary 
df.describe()

,lat,lon,gps_accuracy_m,sequence_no,distance_from_home_m
count,121931.000000,121931.000000,121931.000000,121931.000000,121931.000000
mean,21.132799,79.065911,7.337506,136.154497,4791.803411
std,0.038702,0.027498,2.547589,92.374090,4384.634231
min,21.039423,79.009482,3.000000,0.000000,0.200000
25%,21.120070,79.050158,5.100000,60.000000,2439.050000
50%,21.139507,79.064163,7.300000,121.000000,3491.700000
75%,21.160089,79.080031,9.500000,198.000000,5398.050000
max,21.169191,79.105890,12.000000,388.000000,17443.300000

In [11]:
# catograical summary
df.describe(include="object")

,timestamp,activity,device_id,persona,device_os,ping_id,date,day_of_week
count,121931,121931,121931,121931,121931,121931,121931,121931
unique,1196,9,500,3,2,121931,2,2
top,2026-08-10 13:48:00,Home,70c5ea3b-041b-434e-a324-68e512f7dcf1,Commuter,Android,1dbbb33c-6cc3-4104-89ce-6d345d88d972,2026-08-10,Monday
freq,180,50490,389,72396,81864,1,119243,119243

In [12]:
# checking all missing values
missing_values = df.isnull().sum()

missing_values

lat                     0
lon                     0
timestamp               0
activity                0
device_id               0
persona                 0
device_os               0
gps_accuracy_m          0
ping_id                 0
sequence_no             0
date                    0
day_of_week             0
distance_from_home_m    0
dtype: int64

In [13]:
# Missing-value percentage
missing_percentage = (
    df.isnull().sum()
    / len(df)
    * 100
).round(2)

missing_percentage

lat                     0.0
lon                     0.0
timestamp               0.0
activity                0.0
device_id               0.0
persona                 0.0
device_os               0.0
gps_accuracy_m          0.0
ping_id                 0.0
sequence_no             0.0
date                    0.0
day_of_week             0.0
distance_from_home_m    0.0
dtype: float64

In [14]:
# Create a missing-value summary table
missing_summary = pd.DataFrame({
    "Missing_Count": df.isnull().sum(),
    "Missing_Percentage": (
        df.isnull().sum() / len(df) * 100
    ).round(2)
})

missing_summary

                      Missing_Count  Missing_Percentage
lat                               0                 0.0
lon                               0                 0.0
timestamp                         0                 0.0
activity                          0                 0.0
device_id                         0                 0.0
persona                           0                 0.0
device_os                         0                 0.0
gps_accuracy_m                    0                 0.0
ping_id                           0                 0.0
sequence_no                       0                 0.0
date                              0                 0.0
day_of_week                       0                 0.0
distance_from_home_m              0                 0.0

In [15]:
# checking duplicate rows
duplicate_count = df.duplicated().sum()
print("Duplicate complete rows:", duplicate_count)

Duplicate complete rows: 0

In [16]:
# Check required columns
expected_columns = [
    "lat",
    "lon",
    "timestamp",
    "activity",
    "device_id",
    "persona",
    "device_os",
    "gps_accuracy_m",
    "ping_id",
    "sequence_no",
    "date",
    "day_of_week",
    "distance_from_home_m"
]

missing_columns = [
    col for col in expected_columns
    if col not in df.columns
]

extra_columns = [
    col for col in df.columns
    if col not in expected_columns
]

print("Missing expected columns:", missing_columns)
print("Extra columns:", extra_columns)

Missing expected columns: []
Extra columns: []

In [18]:
# Check unique devices
unique_devices = df["device_id"].nunique()
print("Unique devices:", unique_devices)

Unique devices: 500

In [19]:
# device record distribution
device_record_counts = (
    df["device_id"]
    .value_counts()
)
device_record_counts.describe()

count    500.000000
mean     243.862000
std       84.825667
min      124.000000
25%      168.000000
50%      204.000000
75%      336.000000
max      389.000000
Name: count, dtype: float64

In [20]:
device_record_counts.head(10)

device_id
70c5ea3b-041b-434e-a324-68e512f7dcf1    389
e2c8c9c8-8d7f-4043-a049-9c5f8aec00d6    388
67bb440f-4cdf-46b0-b480-985b5ae37d96    387
8f0bff0e-f515-4600-b9e9-06a15fe2beb9    385
07f56551-3ce6-4956-9cdb-b04239073572    384
faf0d8a1-7475-4d94-837b-f7ca4af3dce4    381
5a520c18-eed4-424f-9132-70a6c62d089a    380
fdd23ffb-824e-414e-a1f3-146a98f625d7    379
d641afae-42a2-4aed-b60a-b48452478b94    379
839dcd9f-0e71-47ec-997d-f5dd6c533aed    377
Name: count, dtype: int64

In [21]:
# Check personas
df["persona"].value_counts()

persona
Commuter    72396
Resident    34067
Shopper     15468
Name: count, dtype: int64

In [22]:
persona_distribution = (
    df["persona"]
    .value_counts(normalize=True)
    * 100
).round(2)

persona_distribution

persona
Commuter    59.37
Resident    27.94
Shopper     12.69
Name: proportion, dtype: float64

In [23]:
# Check device operating systems
df["device_os"].value_counts()

device_os
Android    81864
ios        40067
Name: count, dtype: int64

In [24]:
(
    df["device_os"]
    .value_counts(normalize=True)
    * 100
).round(2)

device_os
Android    67.14
ios        32.86
Name: proportion, dtype: float64

In [25]:
# Standardize OS values
df["device_os"] = (
    df["device_os"]
    .astype(str)
    .str.strip()
    .replace({
        "ios": "iOS",
        "IOS": "iOS",
        "android": "Android"
    })
)

In [26]:
df["device_os"].value_counts()

device_os
Android    81864
iOS        40067
Name: count, dtype: int64

In [27]:
# check activities
df["activity"].value_counts()

activity
Home               50490
Work               25499
Commute to Work    12840
Commute to Home    12840
Return Home         7260
Local Activity      4184
Local Movement      4180
Travel to Store     3080
Shopping            1558
Name: count, dtype: int64

In [28]:
# Clean text columns
text_columns = [
    "device_id",
    "persona",
    "activity",
    "device_os",
    "ping_id",
    "day_of_week"
]

for column in text_columns:
    df[column] = (
        df[column]
        .astype(str)
        .str.strip()
    )

In [29]:
# Convert GPS coordinates to numeric
df["lat"] = pd.to_numeric(
    df["lat"],
    errors="coerce"
)

df["lon"] = pd.to_numeric(
    df["lon"],
    errors="coerce"
)

In [30]:
df[["lat", "lon"]].dtypes

lat    float64
lon    float64
dtype: object

In [31]:
# Convert GPS accuracy
df["gps_accuracy_m"] = pd.to_numeric(
    df["gps_accuracy_m"],
    errors="coerce"
)

In [32]:
# Convert distance from home
df["distance_from_home_m"] = pd.to_numeric(
    df["distance_from_home_m"],
    errors="coerce"
)

In [33]:
# Convert sequence number
df["sequence_no"] = pd.to_numeric(
    df["sequence_no"],
    errors="coerce"
)

In [34]:
# Convert timestamp
df["timestamp"] = pd.to_datetime(
    df["timestamp"],
    errors="coerce"
)

In [35]:
df["timestamp"].dtype

dtype('<M8[ns]')

In [36]:
# Convert date
df["date"] = pd.to_datetime(
    df["date"],
    errors="coerce"
).dt.date

In [37]:
# Check invalid timestamps
invalid_timestamp_count = df["timestamp"].isna().sum()

print(
    "Invalid timestamps:",
    invalid_timestamp_count
)

Invalid timestamps: 0

In [38]:
# Check latitude validity
invalid_lat = (
    (df["lat"] < -90) |
    (df["lat"] > 90) |
    df["lat"].isna()
)

print(
    "Invalid latitude records:",
    invalid_lat.sum()
)

Invalid latitude records: 0

In [39]:
# Check longitude validity
invalid_lon = (
    (df["lon"] < -180) |
    (df["lon"] > 180) |
    df["lon"].isna()
)

print(
    "Invalid longitude records:",
    invalid_lon.sum()
)

Invalid longitude records: 0

In [40]:
# Remove invalid GPS records
df = df[
    ~invalid_lat &
    ~invalid_lon
].copy()

df.reset_index(drop=True, inplace=True)

print("Dataset shape after GPS validation:", df.shape)

Dataset shape after GPS validation: (121931, 13)

In [41]:
# Validate GPS accuracy

print(
    "Minimum GPS accuracy:",
    df["gps_accuracy_m"].min()
)

print(
    "Maximum GPS accuracy:",
    df["gps_accuracy_m"].max()
)

Minimum GPS accuracy: 3.0
Maximum GPS accuracy: 12.0

In [42]:
invalid_accuracy = (
    (df["gps_accuracy_m"] <= 0) |
    df["gps_accuracy_m"].isna()
)

print(
    "Invalid GPS accuracy records:",
    invalid_accuracy.sum()
)

Invalid GPS accuracy records: 0

In [43]:
# Validate distance from home

invalid_distance = (
    (df["distance_from_home_m"] < 0) |
    df["distance_from_home_m"].isna()
)

print(
    "Invalid distance records:",
    invalid_distance.sum()
)

Invalid distance records: 0

In [44]:
# Validate sequence numbers

print(
    "Minimum sequence number:",
    df["sequence_no"].min()
)

print(
    "Maximum sequence number:",
    df["sequence_no"].max()
)

Minimum sequence number: 0
Maximum sequence number: 388

In [45]:
# checking missing sequence values
print(
    "Missing sequence numbers:",
    df["sequence_no"].isna().sum()
)

Missing sequence numbers: 0

In [46]:
# Validate ping IDs

print(
    "Total rows:",
    len(df)
)

print(
    "Unique ping IDs:",
    df["ping_id"].nunique()
)

Total rows: 121931
Unique ping IDs: 121931

In [47]:
duplicate_ping_ids = (
    df["ping_id"].duplicated().sum()
)

print(
    "Duplicate ping IDs:",
    duplicate_ping_ids
)

Duplicate ping IDs: 0

In [48]:
# Check duplicate device/timestamp combinations

duplicate_device_time = df.duplicated(
    subset=[
        "device_id",
        "timestamp"
    ]
).sum()

print(
    "Duplicate device-timestamp records:",
    duplicate_device_time
)

Duplicate device-timestamp records: 0

In [49]:
# Sort the dataset

df = df.sort_values(
    by=[
        "device_id",
        "timestamp",
        "sequence_no"
    ]
).reset_index(drop=True)

In [50]:
# Recalculate temporal features

df["date"] = df["timestamp"].dt.date

df["hour"] = df["timestamp"].dt.hour

df["minute"] = df["timestamp"].dt.minute

df["day_of_week"] = (
    df["timestamp"]
    .dt.day_name()
)

In [51]:
# Create time period

def get_time_period(hour):

    if 7 <= hour < 10:
        return "Morning"

    elif 10 <= hour < 16:
        return "Afternoon"

    elif 16 <= hour < 20:
        return "Evening"

    else:
        return "Night"


df["time_period"] = (
    df["hour"]
    .apply(get_time_period)
)

In [52]:
df["time_period"].value_counts()

time_period
Afternoon    57666
Morning      25472
Evening      20127
Night        18666
Name: count, dtype: int64

In [53]:
# Final missing-value check

final_missing = pd.DataFrame({
    "Missing_Count": df.isnull().sum(),
    "Missing_Percentage": (
        df.isnull().sum() /
        len(df) *
        100
    ).round(2)
})

final_missing

                      Missing_Count  Missing_Percentage
lat                               0                 0.0
lon                               0                 0.0
timestamp                         0                 0.0
activity                          0                 0.0
device_id                         0                 0.0
persona                           0                 0.0
device_os                         0                 0.0
gps_accuracy_m                    0                 0.0
ping_id                           0                 0.0
sequence_no                       0                 0.0
date                              0                 0.0
day_of_week                       0                 0.0
distance_from_home_m              0                 0.0
hour                              0                 0.0
minute                            0                 0.0
time_period                       0                 0.0

In [54]:
# Final duplicate check

print(
    "Final duplicate rows:",
    df.duplicated().sum()
)

print(
    "Final duplicate ping IDs:",
    df["ping_id"].duplicated().sum()
)

Final duplicate rows: 0
Final duplicate ping IDs: 0

In [56]:
# Final dataset structure
print("Final rows:", df.shape[0])
print("Final columns:", df.shape[1])

print("\nFinal columns:")

for i, column in enumerate(df.columns, start=1):
    print(i, "→", column)

Final rows: 121931
Final columns: 16

Final columns:
1 → lat
2 → lon
3 → timestamp
4 → activity
5 → device_id
6 → persona
7 → device_os
8 → gps_accuracy_m
9 → ping_id
10 → sequence_no
11 → date
12 → day_of_week
13 → distance_from_home_m
14 → hour
15 → minute
16 → time_period

In [57]:
# Final data types
df.dtypes

lat                            float64
lon                            float64
timestamp               datetime64[ns]
activity                        object
device_id                       object
persona                         object
device_os                       object
gps_accuracy_m                 float64
ping_id                         object
sequence_no                      int64
date                            object
day_of_week                     object
distance_from_home_m           float64
hour                             int32
minute                           int32
time_period                     object
dtype: object

In [58]:
# Final Preview

df.head(10)

,lat,lon,timestamp,activity,device_id,persona,device_os,gps_accuracy_m,ping_id,sequence_no,date,day_of_week,distance_from_home_m,hour,minute,time_period
0,21.168807,79.105546,2026-08-10 07:20:00,Home,00375ad6-ba48-4d2e-9776-65e73b91851c,Commuter,Android,5.0,f02e32c3-9646-4ae6-abac-c98bce6a92cb,0,2026-08-10,Monday,5408.7,7,20,Morning
1,21.168761,79.105350,2026-08-10 07:23:00,Home,00375ad6-ba48-4d2e-9776-65e73b91851c,Commuter,Android,5.0,2ce40791-eed2-44f0-8a97-aa29ef2111e2,1,2026-08-10,Monday,5389.4,7,23,Morning
2,21.168779,79.105398,2026-08-10 07:26:00,Home,00375ad6-ba48-4d2e-9776-65e73b91851c,Commuter,Android,5.0,d615c4f1-cead-420e-a1dd-319845058fa4,2,2026-08-10,Monday,5394.6,7,26,Morning
3,21.168789,79.105182,2026-08-10 07:29:00,Home,00375ad6-ba48-4d2e-9776-65e73b91851c,Commuter,Android,5.0,3f7186c1-f5bb-4718-a78f-c5f48ce8a235,3,2026-08-10,Monday,5377.5,7,29,Morning
4,21.169002,79.105322,2026-08-10 07:32:00,Home,00375ad6-ba48-4d2e-9776-65e73b91851c,Commuter,Android,5.0,546486fa-a442-4007-8b35-09963208ba2c,4,2026-08-10,Monday,5403.4,7,32,Morning
5,21.168636,79.105137,2026-08-10 07:35:00,Home,00375ad6-ba48-4d2e-9776-65e73b91851c,Commuter,Android,5.0,3a243587-d659-4eb5-a513-05436a5bf5dc,5,2026-08-10,Monday,5363.4,7,35,Morning
6,21.168655,79.105385,2026-08-10 07:38:00,Home,00375ad6-ba48-4d2e-9776-65e73b91851c,Commuter,Android,5.0,65a41ca0-6398-4138-bd23-2408fe93938f,6,2026-08-10,Monday,5385.2,7,38,Morning
7,21.168721,79.105272,2026-08-10 07:41:00,Home,00375ad6-ba48-4d2e-9776-65e73b91851c,Commuter,Android,5.0,76b70e7b-5854-4439-a2f0-2245983610e1,7,2026-08-10,Monday,5380.4,7,41,Morning
8,21.168674,79.105158,2026-08-10 07:44:00,Home,00375ad6-ba48-4d2e-9776-65e73b91851c,Commuter,Android,5.0,f2c17bc7-162f-47d3-a030-fbaea649f736,8,2026-08-10,Monday,5367.8,7,44,Morning
9,21.168426,79.105103,2026-08-10 07:47:00,Home,00375ad6-ba48-4d2e-9776-65e73b91851c,Commuter,Android,5.0,980a0bea-628e-45fd-ace1-2e338eeff38a,9,2026-08-10,Monday,5346.5,7,47,Morning

In [59]:
# Create processed directory
os.makedirs(
    "data/processed",
    exist_ok=True
)

In [60]:
# Saving the cleaned CSV
OUTPUT_FILE = "data/processed/gps_final_clean.csv"

df.to_csv(
    OUTPUT_FILE,
    index=False
)

print("Clean dataset saved successfully!")
print("Location:", OUTPUT_FILE)
print("Final shape:", df.shape)

Clean dataset saved successfully!
Location: data/processed/gps_final_clean.csv
Final shape: (121931, 16)